# Generated by Django 4.1.5 on 2023-04-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
