# Generated by Django 4.1.5 on 2023-04-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0002_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
