# Generated by Django 4.2 on 2023-05-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0004_alter_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='Uploads/avatar/1.png', upload_to='Uploads/avatar/'),
        ),
    ]
