# Generated by Django 4.2 on 2023-05-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0010_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
