# Generated by Django 4.2 on 2023-06-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0012_question_correct_answer_alter_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='media/Uploads/avatar/1.png', upload_to='media/Uploads/avatar/'),
        ),
    ]
